name: Publish package to GitHub Packages (Gradle)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Publish package
        run: ./gradlew publish
        env: 
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ORG: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
